apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clteoweatherapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clteoweatherapp.name" . }}
    helm.sh/chart: {{ include "clteoweatherapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas:  {{ include "clteoweatherapp.replicas" . }} 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clteoweatherapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clteoweatherapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: APP_DEFAULT_ID
          value: {{ default "Singapore" .Values.APP_DEFAULT_CITY }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

 