apiVersion: v1
kind: ServiceAccount

metadata:
  name: webui-admin
  namespace: myspace

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: webui-admin-crb
  namespace: myspace

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: webui-admin
  namespace: myspace

  subjects:
  -kind: ServiceAccount
    name: webui-admin
    namespace: myspace


