# Default values for clteoweatherapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

deployment: 
  containerPort: 3000

APP_ID: ecbd92ff90840c3a36dad8d16f7f7fb2

productionEnv: true
productionReplicaCount: 2   
APP_DEFAULT_CITY: JAPAN

gatewayhostname: "jp.157.230.73.81.nip.io"  
gatewayport: 80

